name: CloudLab CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  NODE_APP_IMAGE: cloudlab-nodejs-app
  PYTHON_APP_IMAGE: cloudlab-python-app

jobs:
  # Lint and validate configurations
  validate:
    name: Validate Configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker-compose config

      - name: Validate Nginx config
        run: |
          docker run --rm -v $(pwd)/nginx/nginx.conf:/etc/nginx/nginx.conf:ro nginx:alpine nginx -t

  # Build Node.js application
  build-nodejs:
    name: Build Node.js App
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Node.js Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/demo-apps/nodejs-app
          file: ./apps/demo-apps/nodejs-app/Dockerfile
          push: false
          tags: ${{ env.NODE_APP_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Node.js app
        run: |
          docker run -d --name test-nodejs -p 3001:3001 ${{ env.NODE_APP_IMAGE }}:${{ github.sha }}
          sleep 5
          curl -f http://localhost:3001/health || exit 1
          curl -f http://localhost:3001/metrics || exit 1
          docker stop test-nodejs
          docker rm test-nodejs

  # Build Python application
  build-python:
    name: Build Python App
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Python Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/demo-apps/python-app
          file: ./apps/demo-apps/python-app/Dockerfile
          push: false
          tags: ${{ env.PYTHON_APP_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Python app
        run: |
          docker run -d --name test-python -p 5000:5000 ${{ env.PYTHON_APP_IMAGE }}:${{ github.sha }}
          sleep 10
          curl -f http://localhost:5000/api/health || exit 1
          curl -f http://localhost:5000/metrics || exit 1
          docker stop test-python
          docker rm test-python

  # Security scanning
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: [build-nodejs, build-python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner - Node.js
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "./apps/demo-apps/nodejs-app"
          format: "sarif"
          output: "trivy-nodejs-results.sarif"

      - name: Run Trivy vulnerability scanner - Python
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "./apps/demo-apps/python-app"
          format: "sarif"
          output: "trivy-python-results.sarif"

  # Integration test
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [build-nodejs, build-python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start all services
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: |
          sleep 30
          docker-compose ps

      - name: Test Nginx reverse proxy
        run: |
          curl -k -f https://localhost/health || exit 1

      - name: Test Node.js app through Nginx
        run: |
          curl -k -f https://localhost/ || exit 1

      - name: Test Python API through Nginx
        run: |
          curl -k -f https://localhost/api || exit 1

      - name: Test Prometheus
        run: |
          curl -f http://localhost:9090/-/healthy || exit 1

      - name: Test Grafana
        run: |
          curl -f http://localhost:3000/api/health || exit 1

      - name: Check Prometheus targets
        run: |
          curl -f http://localhost:9090/api/v1/targets | grep -q "nodejs-app"
          curl -f http://localhost:9090/api/v1/targets | grep -q "python-app"

      - name: Show logs on failure
        if: failure()
        run: docker-compose logs

      - name: Cleanup
        if: always()
        run: docker-compose down -v

  # Deployment (optional - uncomment when ready)
  # deploy:
  #   name: Deploy to Environment
  #   runs-on: ubuntu-latest
  #   needs: [integration-test, security-scan]
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Deploy to production
  #       run: |
  #         echo "Add your deployment steps here"
